language: node_js
node_js:
  - "0.10"

notifications:
  email:
    recipients:
      - kezho@me.com
    on_success: change
    on_failure: always

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - npm install --quiet -g grunt-cli karma bower
  - bower install

script: grunt
